services:
  nats:
    image: nats:2.10.24-alpine3.21
    container_name: nats
    profiles:
      - dev
      - integration-test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M
    command:
      - -client_advertise
      - nats:4222
      - --user
      - dev
      - --pass
      - dev

  nats-cluster-1:
    image: nats:2.10.24-alpine3.21
    container_name: nats-1
    profiles:
      - dev
      - integration-test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M
    command:
      - -client_advertise
      - nats-1:4222
      - --cluster_name
      - nuts-dev-cluster
      - --cluster
      - nats://0.0.0.0:6222
      - --http_port
      - '8222'

  nats-cluster-2:
    image: nats:2.10.24-alpine3.21
    container_name: nats-2
    profiles:
      - dev
      - integration-test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M
    command:
      - -client_advertise
      - nats-2:4222
      - --cluster_name
      - nuts-dev-cluster
      - --cluster
      - nats://0.0.0.0:6222
      - --routes=nats://nats-1:6222,nats://nats-3:6222

  nats-cluster-3:
    image: nats:2.10.24-alpine3.21
    container_name: nats-3
    profiles:
      - dev
      - integration-test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M
    command:
      - -client_advertise
      - nats-3:4222
      - --cluster_name
      - nuts-dev-cluster
      - --cluster
      - nats://0.0.0.0:6222
      - --routes=nats://nats-1:6222,nats://nats-2:6222

  tarantool-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: tarantool-dev
    profiles:
      - dev
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M

  tarantool-integration-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: integration-tests
    container_name: tarantool-integration-test-1
    profiles:
      - integration-test
    ports:
      - '127.0.0.1:3301:3301'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '0.25'
          memory: 256M

  tester-integration:
    build:
      context: tests/integration/tester-python
      dockerfile: Dockerfile
    container_name: tester-integration
    profiles:
      - integration-test
    ports:
      - '127.0.0.1:8080:8080'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M

  tarantool-unit-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: unit-tests
    container_name: tarantool-unit-test
    profiles:
      - unit-test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      TT_CONFIG:
      TT_INSTANCE_NAME:
#    command: [".rocks/bin/luatest", "./tests", "-v", "-c", "-o", "junit", "-n", "/results/report"]
    command: [".rocks/bin/luatest", "./tests", "-o", "junit", "-n", "/results/report"]
    volumes:
      - ./tests/results:/results

  tarantool-coverage:
    build:
      context: .
      dockerfile: Dockerfile
      target: unit-tests
    container_name: tarantool-coverage
    profiles:
      - coverage
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      TT_CONFIG:
      TT_INSTANCE_NAME:
    command: [ "/bin/sh", "-c",  ".rocks/bin/luatest ./tests --coverage; .rocks/bin/luacov .; grep -A999 '^Summary' /results/luacov.report.out" ]
    volumes:
      - ./tests/results:/results


networks:
  default:
    name: tarantool-nats-connector