== Подключение к NATS

* Подключение библиотеки:
----
local nats = require('nats')
----
* Создание клиента:
----
local nc = nats.NatsClient.new('nats://127.0.0.1:4222', { ping_interval = 5, max_outstanding_pings = 2 })
----

=== Функция new
Принимает на вход следующие параметры:

* Первый параметр - строка или список строк, url серверов NATS;
* Второй параметр - словарь содержащий следующие элементы:
** error_cb - функция вызываемая при ошибках, по умолчанию пишет ошибку в лог;
** disconnected_cb - функция вызываемая при отключении от сервера, не обязательный параметр;
** closed_cb - функция вызываемая при закрытии клиента, не обязательный параметр;
** discovered_server_cb - функция вызываемая при появлении нового сервера в кластере, не обязательный параметр;
** reconnected_cb - функция вызываемая при переподключении к серверу, не обязательный параметр;
** name - строка, имя соединения (отображается в мониторинге NATS), не обязательный параметр;
** pedantic - булево значение, включает дополнительную строгую проверку формата, например, для правильно сформированных тем, по умолчанию `false`;
** verbose - булево значение, включает подтверждения протокола +OK, по умолчанию `false`;
** allow_reconnect - булево значение, возможность повторного подключения к серверам, по умолчанию `true`;
** connect_timeout - число, таймаут подключения к серверу в секундах, по умолчанию `2`;
** reconnect_time_wait - число, время ожидания между попытками подключения к серверу, по умолчанию `2`;
** max_reconnect_attempts - число, максимальное количество попыток подключиться к серверу, по умолчанию `60`;
** ping_interval - число, интервал между отправками сообщения PING на сервер в секундах, по умолчанию `120`;
** max_outstanding_pings - число, количество не полученных ответов на PING перед отключением от сервера, по умолчанию `2`;
** dont_randomize - булево значение, не перемешивать сервера в списке, по умолчанию `false`;
** no_echo - булево значение, если установлено значение true, сервер (версия 1.2.0+) не будет отправлять исходные сообщения из этого соединения в свои собственные подписки. Клиенты должны устанавливать значение true только для сервера, поддерживающего эту функцию, то есть, когда proto в протоколе INFO установлено как минимум на 1, по умолчанию `false`;
** user - строка, имя пользователя для подключения, не обязательный параметр;
** password - строка, пароль для подключения, не обязательный параметр;
** drain_timeout - число, ожидание корректного отключения от сервера в секундах, по умолчанию `30`;
** inbox_prefix - строка, префикс для автоматически создаваемых subject, по умолчанию `_INBOX`;
** pending_size - число, максимальный размер ожидающего буфера для публикации команд в битах, по умолчанию `2 * 1024 * 1024`;
** flush_timeout - число, тайм-аут очистки ожидающего буфера в секундах, по умолчанию `10`;
** flusher_queue_size - число, размер очереди обработчика отчистки, по умолчанию `1024`;

Возвращает <<client>>.

[[client]]
=== Сущность client
Имеет следующие параметры:

* stats - словарь <строка, число>, статистика клиента:
** in_msgs - количество полученных сообщений;
----
nc.stats.in_msgs
----
** out_msgs - количество отправленных сообщений;
----
nc.stats.out_msgs
----
** in_bytes - количество полученных байт (учитывается только полезная нагрузка);
----
nc.stats.in_bytes
----
** out_bytes - количество отправленных байт (учитывается только полезная нагрузка);
----
nc.stats.out_bytes
----
** reconnects - количество переподключений к серверам;
----
nc.stats.reconnects
----
** errors_received - количество полученных ошибок от серверов;
----
nc.stats.errors_received
----

Имеет следующие методы:

* close - очищает очереди и отключается от сервера:
----
nc:close()
----
* drain - закрывает подписки, очищает очереди и отключается от сервера:
----
nc:drain()
----
* flush - принимает таймаут ожидания ответа типа число, отправляет все данные и PING на сервер и ожидает ответа на PING:
----
nc:flush(1)
----
* publish - <<fun-publish>>;
* subscribe - <<fun-subscribe>>;
* new_inbox - генерирует уникальное имя subject:
----
nc:new_inbox()
---
- _INBOX.4VqiDsBkES3BVUYBfiAnIC
...
----
* request - <<fun-reqest>>;
* connected_url - возвращает url сервера к которому подключен клиент:
----
nc:connected_url()
---
- host: nats-1
  service: '4222'
  scheme: nats
...
----
* servers - возвращает url's всех доступных серверов:
----
nc:servers()
---
- - host: nats-3
    service: '4222'
  - host: nats-2
    service: '4222'
  - host: nats-1
    service: '4222'
    scheme: nats
...
----
* discovered_servers - возвращает url's серверов подключенных к кластеру:
----
nc:discovered_servers()
---
- - host: nats-3
    service: '4222'
  - host: nats-2
    service: '4222'
...
----
* max_payload - возвращает размер максимальной полезной нагрузки которую поддерживает сервер:
----
nc:max_payload()
---
- 1048576
...
----
* client_id - возвращает уникальный идентификатор клиента:
----
nc:client_id()
---
- 14
...
----
* last_error - возвращает последнюю ошибку:
----
nc:last_error()
----
* is_closed - возвращает true, если клиент закрыл подключение к серверу NATS:
----
nc:is_closed()
---
- false
...
----
* is_reconnecting - возвращает true, если клиент в состоянии переподключения к серверу NATS:
----
nc:is_reconnecting()
---
- false
...
----
* is_connected - возвращает true, если клиент в подключен к серверу NATS:
----
nc:is_connected()
---
- true
...
----
* is_connecting - возвращает true, если клиент в состоянии подключения к серверу NATS:
----
nc:is_connecting()
---
- false
...
----
* is_draining - возвращает true, если клиент в состоянии очистки очередей:
----
nc:is_draining()
---
- false
...
----
* is_draining_pubs - возвращает true, если клиент в состоянии очистки очереди отправляемых сообщений:
----
nc:is_draining_pubs()
---
- false
...
----
* connected_server_version - возвращает версию NATS сервера к которому подключен клиент:
----
nc:connected_server_version()
---
- patch: 24
  minor: 10
  major: 2
  prefix:
...
----

== Отправка сообщения в NATS

----
nc:publish('test.1', 'test payload', 'test.reply', { a = 'b' })
----

[[fun-publish]]
=== Функция publish
Принимает на вход следующие параметры:

* Первый параметр - строка, subject в который отправляется сообщений, обязательный параметр;
* Второй параметр - строка, полезная нагрузка сообщения, обязательный параметр;
* Третий параметр - строка, subject в который ожидается ответ на сообщение, не обязательный параметр;
* Четвертый параметр - словарь `{ строка, строка }`, заголовки сообщения, не обязательный параметр;

== Подписка на subject

----
function sub_cb(message)
    if message.reply and message.reply ~= '' then
        message:respond('test pong')
    end
end

sub = nc:subscribe('test.1', 'test', sub_cb, 10, 1000, 10000)
----

[[fun-subscribe]]
=== Функция subscribe
Принимает на вход следующие параметры:

* Первый параметр - строка, subject из которого получать сообщений, обязательный параметр;
* Второй параметр - строка, очередь подписчиков (из всех подписчиков в очереди сообщение получит только один), не обязательный параметр;
* Третий параметр - функция, на вход получает сообщение и обрабатывает его согласно написанной логике, не обязательный параметр;
* Четвертый параметр - число, количество сообщений после получения которого клиент автоматически отпишется, не обязательный параметр;
* Пятый параметр - число, максимальное количество сообщений в очереди обработчика, по умолчанию `512 * 1024`;
* Шестой параметр - число, максимальное количество байтов в очереди обработчика, по умолчанию `128 * 1024 * 1024`;

Возвращает <<subscription>>.

[[subscription]]
=== Сущность subscription
Имеет следующие методы:

* subject - возвращает имя subject:
----
sub:subject()
---
- test.1
...
----
* queue - возвращает имя очереди подписчиков:
----
sub:queue()
---
- test
...
----
* messages - возвращает функцию итератор по полученным сообщениям (если при подписке не определена функция обработчик):
----
log = require('log')
for msg in sub:messages() do
    log.info(msg.payload)
end
----
* pending_msgs - возвращает количество сообщений в очереди на обработку:
----
sub:pending_msgs()
---
- 2
...
----
* pending_bytes - возвращает количество байт в очереди на обработку:
----
sub:pending_bytes()
---
- 24
...
----
* delivered - возвращает количество полученных сообщений:
----
sub:delivered()
---
- 2
...
----
* next_msg - возвращает следующее сообщение из очереди (<<message>>) (если при подписке не определена функция обработчик):
----
msg = sub:next_msg()
----
* drain - очищает очередь сообщений и останавливает подписку:
----
sub:drain()
----
* unsubscribe - отписывается от подписки:
----
sub:unsubscribe()
----

== Отправка запроса в NATS с ожиданием ответа

----
msg = nc:request('test.1', 'test ping', { test = 'test' }, 2)
----

[[fun-reqest]]
=== Функция request
Принимает на вход следующие параметры:

* Первый параметр - строка, subject в который отправляется сообщение, обязательный параметр;
* Второй параметр - строка, полезная нагрузка сообщения, обязательный параметр;
* Третий параметр - словарь `{ строка, строка }`, заголовки сообщения, не обязательный параметр;
* Четвертый параметр - число, таймаут ожидания ответа в секундах, не обязательный параметр (если не указан или nil, то время ожидания не ограничено);

Возвращает <<message>>.

[[message]]
=== Сущность message
Имеет следующие параметры:

* subject - строка, subject в который поступило сообщение:
----
msg.subject
----
* reply - строка, subject в котором ожидается ответ на сообщение (может быть nil или пустой строкой):
----
msg.reply
----
* payload - строка, полезная нагрузка сообщения:
----
msg.payload
----

Имеет следующие методы:

* header - возвращает таблицу <строка, строка> с заголовками сообщения:
----
headers = msg:header()
----
* sid - возвращает уникальный идентификатор подписки типа число:
----
sid = msg:sid()
----
* respond - на вход принимает параметр типа строка, полезную нагрузку и отправляет ответ в топик `msg.reply`:
----
msg:respond('response')
----

